### PR TITLE
Support PowerShell completions

### PR DESCRIPTION
**Pull request by jcwillox**
I've done some initial work to add support for (un)installing and generating PowerShell completions files. The actual completion script is derived from [cobra](https://github.com/spf13/cobra/blob/main/powershell_completions.go)  and [pnpm.ps1](https://gist.github.com/jcwillox/027b6c105d190abfa0333c13836f5bec).

This PR is related to https://github.com/pnpm/pnpm/issues/3771 and https://github.com/mklabs/tabtab/issues/26.

The PR currently uses the default profile location for PSv6+, and won't install completions in the correct location for users of PSv5. The method for identifying the shell discussed below would allow for detecting the correct location.

* **6+**: ~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1
* **5**: ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1

Currently, the main issue with this PR is that is cannot detect whether the user is running PowerShell, as PowerShell does not set the `SHELL` environment variable. This means that while uninstalling does technically work, the shell must be explicitly set.
The completion script currently sets `SHELL=pwsh` to work around this.

There is of course a way to detect PowerShell, I need to update the `systemShell` function to identify the shell based on the parent processes executable. This, however, requires an additional dependency, https://www.npmjs.com/package/find-process, looks like a good choice. Additionally, there's the question of whether we'd still respect the `SHELL` variable, as it usually represents the users login shell and not necessarily their current shell.

### CODE REVIEW

**Comment by so1ve** [comment]
hi, is this pr dead?

**Comment by jcwillox** [comment]
Well I'm still here if anyone wants to review this, and in the meantime if you need PowerShell completions there's still this script I made which should work well https://gist.github.com/jcwillox/027b6c105d190abfa0333c13836f5bec

**Comment by so1ve** [comment]
> Well I'm still here if anyone wants to review this, and in the meantime if you need PowerShell completions there's still this script I made which should work well https://gist.github.com/jcwillox/027b6c105d190abfa0333c13836f5bec

thanks for your awesome work! I want to fork pnpm's tabtab and publish a new tabtab package. may I use your code to support powershell?

**Review by so1ve — COMMENTED** [review]
one question: could "~" be resolved on windows?

**Review by so1ve — APPROVED** [review]

**Comment by jcwillox** [comment]
> thanks for your awesome work! I want to fork pnpm's tabtab and publish a new tabtab package. may I use your code to support powershell?

Yeah go for it, I'm fine with that. Do you think there's much point in creating this PR on [mklabs/tabtab](https://github.com/mklabs/tabtab) instead, or is that repo sort of dead?

> one question: could "~" be resolved on windows?

It usually is resolved correctly in most languages, and I'm sure it is in this case, as it must have worked in my testing. It should be resolved to `C:\Users\<username>` on Windows.

**Comment by so1ve** [comment]
> Do you think there's much point in creating this PR on [mklabs/tabtab](https://github.com/mklabs/tabtab) instead, or is that repo sort of dead?

I think it is no longer active :(

> It usually is resolved correctly in most languages, and I'm sure it is in this case, as it must have worked in my testing. It should be resolved to `C:\Users\<username>` on Windows.

Thanks!

**Review by zkochan — APPROVED** [review]

**Comment by zkochan** [comment]
Sorry for not noticing this PR. Usually I only check the main repository for contributions.

**Comment by zkochan** [comment]
Looks like the tests fail on the main branch after merging this.

**Comment by KSXGitHub** [comment]
@jcwillox The powershell template you submitted doesn't make use of `{completer}`. Can you submit a PR to fix this?

**Comment by jcwillox** [comment]
Yes sorry been a while since this ticket was touched, I'll have a look into the issues tonight/tomorrow

**Comment by KSXGitHub** [comment]
@jcwillox Have you looked into it yet?

**Pull request merged**
